// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'label': string;
  'metricWrap': string;
  'primary': string;
  'secondary': string;
  'unit': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
