// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backBtn': string;
  'bondProgress': string;
  'bondProgressFill': string;
  'bondProgressHealthy': string;
  'bondProgressLow': string;
  'bondProgressNone': string;
  'bondProgressWatch': string;
  'copiedFeedback': string;
  'detailCol': string;
  'detailColTitle': string;
  'detailGrid': string;
  'detailRow': string;
  'detailRowLabel': string;
  'detailRowValue': string;
  'header': string;
  'pubkey': string;
  'rankBadge': string;
  'recommendationBox': string;
  'recommendationLabel': string;
  'recommendationText': string;
  'simulationCta': string;
  'simulationCtaBtn': string;
  'simulationCtaText': string;
  'summaryCard': string;
  'summaryCardHealthy': string;
  'summaryCardLabel': string;
  'summaryCardLow': string;
  'summaryCardNone': string;
  'summaryCardSub': string;
  'summaryCardValue': string;
  'summaryCardWatch': string;
  'summaryCards': string;
  'validatorName': string;
}
export const cssExports: CssExports;
export default cssExports;
