// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dot': string;
  'dotHalo': string;
  'line': string;
  'svg': string;
}
export const cssExports: CssExports;
export default cssExports;
