// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'container': string;
  'tooltip': string;
  'trigger': string;
}
export const cssExports: CssExports;
export default cssExports;
