// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'container': string;
  'label': string;
  'unit': string;
  'value': string;
  'valueContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
