// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'apyBar': string;
  'apyLegend': string;
  'apySegment': string;
  'bondBalance': string;
  'bondCard': string;
  'bondHeader': string;
  'bondMetric': string;
  'bondMetricLabel': string;
  'bondMetricValue': string;
  'bondMetrics': string;
  'bondStatus': string;
  'closeBtn': string;
  'constraintText': string;
  'content': string;
  'dot': string;
  'gaugeBar': string;
  'gaugeContainer': string;
  'gaugeFill': string;
  'gaugeLabels': string;
  'gaugeLine': string;
  'header': string;
  'headerLeft': string;
  'leftColumn': string;
  'overlay': string;
  'panel': string;
  'rank': string;
  'rightColumn': string;
  'section': string;
  'sectionTitle': string;
  'simButton': string;
  'simField': string;
  'simForm': string;
  'slideIn': string;
  'stakeLabel': string;
  'stakeMetric': string;
  'stakeMetrics': string;
  'stakeValue': string;
  'statusBadge': string;
  'tipCard': string;
  'tipIcon': string;
  'tipText': string;
  'voteAccount': string;
  'winningLabel': string;
}
export const cssExports: CssExports;
export default cssExports;
