// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bg-danger': string;
  'bg-warning': string;
  'left': string;
  'noBg': string;
  'right': string;
  'table': string;
}
export const cssExports: CssExports;
export default cssExports;
