// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'barFill': string;
  'barTrack': string;
  'label': string;
  'name': string;
  'pct': string;
  'row': string;
  'rows': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
