// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'metricWrap': string;
  'pubkey': string;
  'tableWrap': string;
}
export const cssExports: CssExports;
export default cssExports;
