// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'docsButton': string;
  'navButton': string;
  'navigation': string;
}
export const cssExports: CssExports;
export default cssExports;
