// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'page': string;
  'pageContent': string;
  'simulationNote': string;
  'simulatorToggle': string;
  'simulatorToggleActive': string;
}
export const cssExports: CssExports;
export default cssExports;
