// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'calculating': string;
  'page': string;
  'pageContent': string;
  'pulse-glow': string;
  'simulationMode': string;
}
export const cssExports: CssExports;
export default cssExports;
