// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badge': string;
  'badgeDryRun': string;
  'badgeEstimate': string;
  'calculating': string;
  'cancelBtn': string;
  'editingButtons': string;
  'ghostRow': string;
  'green': string;
  'header-glow': string;
  'inlineInput': string;
  'inputCell': string;
  'inputPlaceholder': string;
  'metricWrap': string;
  'orderCell': string;
  'originalPosition': string;
  'positionImproved': string;
  'positionUnchanged': string;
  'positionWorsened': string;
  'pubkey': string;
  'pubkeySimulated': string;
  'red': string;
  'runSimulationBtn': string;
  'runSimulationBtnCalculating': string;
  'simulationModeActive': string;
  'simulationNote': string;
  'simulatorToggle': string;
  'simulatorToggleActive': string;
  'simulatorToggleWrap': string;
  'tableWrap': string;
  'validatorRowClickable': string;
  'validatorRowEditing': string;
  'yellow': string;
}
export const cssExports: CssExports;
export default cssExports;
