// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badge': string;
  'badgeDryRun': string;
  'badgeEstimate': string;
  'green': string;
  'inlineInput': string;
  'metricWrap': string;
  'pubkey': string;
  'pubkeySimulated': string;
  'red': string;
  'simulationNote': string;
  'simulatorToggle': string;
  'simulatorToggleActive': string;
  'simulatorToggleWrap': string;
  'tableWrap': string;
  'yellow': string;
}
export const cssExports: CssExports;
export default cssExports;
