// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'left': string;
  'right': string;
  'table': string;
}
export const cssExports: CssExports;
export default cssExports;
