// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'green': string;
  'left': string;
  'noBg': string;
  'red': string;
  'right': string;
  'sortIndicator': string;
  'sortIndicatorActive': string;
  'sortIndicatorDefault': string;
  'table': string;
  'yellow': string;
}
export const cssExports: CssExports;
export default cssExports;
