// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'cancelBtn': string;
  'popover': string;
  'row': string;
  'simulateBtn': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
