// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badge': string;
  'badgeDryRun': string;
  'badgeEstimate': string;
  'metricWrap': string;
  'pubkey': string;
  'tableWrap': string;
}
export const cssExports: CssExports;
export default cssExports;
