// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badge': string;
  'badges': string;
  'metricWrap': string;
  'notif': string;
  'pubkey': string;
  'tableWrap': string;
  'validatorCell': string;
}
export const cssExports: CssExports;
export default cssExports;
