// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bannerShoutout': string;
  'bannerTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
